== Builder Pattern Örneği

.Builder Pattern PlantUML
[plantuml, uml , png]      
....
class Book {
- String isim 
- String yazar
- String sayfaSayisi 
- String basimYili
- String yayınEvi
- String kategori
- String isbn

+ Book()
+ String getIsim() 
+ void setIsim(String) 
+ String getYazar() 
+ void setYazar(String yazar) 
+ String getSayfaSayisi() 
+ void setSayfaSayisi(String) 
+ String getBasimYili() 
+ void setBasimYili(String) 
+ String getYayınEvi()
+ void setYayınEvi(String) 
+ String getKategori() 
+ void setKategori(String) 
+ String getIsbn() 
+ void setIsbn(String) 
+ String getOrnek() 
}

abstract BookBuilder {
+ {abstract} void buildIsim()
+ {abstract} void buildYazar()
+ {abstract} void buildSayfaSayisi() 
+ {abstract} void buildBasimYili()  
+ {abstract} void buildYayınEvi()
+ {abstract} void buildKategori()
+ {abstract} void buildIsbn()
+ {abstract} Book getBook()
}

class BiographyBuilder {
- Book _product 
}
BiographyBuilder --> Book :inşa eder
BiographyBuilder ..|> BookBuilder 

class NovelBuilder {
- Book _product 
}
NovelBuilder --> Book  :inşa eder
NovelBuilder ..|> BookBuilder 

class TaleBuilder {
- Book _product 
}
TaleBuilder --> Book  :inşa eder
TaleBuilder ..|> BookBuilder 

class Reader {
+ void Create(BookBuilder)
    
}
BookBuilder --o Reader

class Main {
+ {static} void main(String[] args
}
Main -- Reader
....


== Kodlar :

****
.Book.java
[source,java]
----
public class Book
{
	//zorunlu
	 private String isim; 
	 private String yazar; 
	 
	//optional
	 private String sayfaSayisi; 
	 private String basimYili;
	 private String yayınEvi;
	 private String kategori; 
	 private String isbn; 
	 
	 public Book() { }

		public String getIsim() {
			return isim;
		}
		public void setIsim(String isim) {
			this.isim = isim;
		}
		public String getYazar() {
			return yazar;
		}
		public void setYazar(String yazar) {
			this.yazar = yazar;
		}
		public String getSayfaSayisi() {
			return sayfaSayisi;
		}
		public void setSayfaSayisi(String sayfaSayisi) {
			this.sayfaSayisi = sayfaSayisi;
		}
		public String getBasimYili() {
			return basimYili;
		}
		public void setBasimYili(String basimYili) {
			this.basimYili = basimYili;
		}
		public String getYayınEvi() {
			return yayınEvi;
		}
		public void setYayınEvi(String yayınEvi) {
			this.yayınEvi = yayınEvi;
		}
		public String getKategori() {
			return kategori;
		}
		public void setKategori(String kategori) {
			this.kategori = kategori;
		}
		public String getIsbn() {
			return isbn;
		}
		public void setIsbn(String isbn) {
			this.isbn = isbn;
		}
		public String getOrnek() {
	    	String instance = "Kitap: "+this.isim+", "+this.yazar+", "+this.sayfaSayisi+", "+this.basimYili+", "
	            +this.yayınEvi+", "+this.kategori+", "+this.isbn+"\n ";
	    	return instance;
	    }
}
----
****

****
.BookBuilder.java
[source,java]
----
public abstract class BookBuilder
{
    public abstract void buildIsim();  
    public abstract void buildYazar(); 
    public abstract void buildSayfaSayisi();  
    public abstract void buildBasimYili();   
    public abstract void buildYayınEvi();
    public abstract void buildKategori();
    public abstract void buildIsbn();
    public abstract Book getBook();
}
----
****

****
.BiographyBuilder.java
[source,java]
----
public class BiographyBuilder  extends BookBuilder
{
    private Book _product = new Book();
	
	@Override
	public void buildIsim() {
		_product.setIsim("Einstein - Yaşamı ve Evreni");
	}
	@Override
	public void buildYazar() {
		_product.setYazar("Walter Isaacson");
	}
	@Override
	public void buildSayfaSayisi() {
		_product.setSayfaSayisi("679");
	}
	@Override
	public void buildBasimYili() {
		_product.setBasimYili("2010");
	}
	@Override
	public void buildYayınEvi() {
		_product.setYayınEvi("Tudem Yayınevi");
	}
	@Override
	public void buildKategori() {
		_product.setKategori("Biyografi");
	}
	@Override
	public void buildIsbn() {
		_product.setIsbn("9944693042");
	}
	@Override
	public Book getBook() {
		return _product;
	}
}
----
****

****
.NovelBuilder.java
[source,java]
----
public class NovelBuilder extends BookBuilder
{
    private Book _product = new Book();
	
	@Override
	public void buildIsim() {
		_product.setIsim("Tutanamayanlar");
	}
	@Override
	public void buildYazar() {
		_product.setYazar("Oğuz Atay");
	}
	@Override
	public void buildSayfaSayisi() {
		_product.setSayfaSayisi("724");
	}
	@Override
	public void buildBasimYili() {
		_product.setBasimYili("2000");
	}
	@Override
	public void buildYayınEvi() {
		_product.setYayınEvi("İletişim Yayıncılık");
	}
	@Override
	public void buildKategori() {
		_product.setKategori("Roman");
	}
	@Override
	public void buildIsbn() {
		_product.setIsbn("9754700114");
	}
	@Override
	public Book getBook() {
		return _product;
	}
}
----
****

****
.TaleBuilder.java
[source,java]
----
public class TaleBuilder extends BookBuilder
{
    private Book _product = new Book();
	
	@Override
	public void buildIsim() {
		_product.setIsim("Dönüşüm");
	}
	@Override
	public void buildYazar() {
		_product.setYazar("Franz Kafka");
	}
	@Override
	public void buildSayfaSayisi() {
		_product.setSayfaSayisi("104");
	}

	@Override
	public void buildBasimYili() {
		_product.setBasimYili("2019");
	}
	@Override
	public void buildYayınEvi() {
		_product.setYayınEvi("Can Yayınları");
	}
	@Override
	public void buildKategori() {
		_product.setKategori("Hikaye");
	}
	@Override
	public void buildIsbn() {
		_product.setIsbn("9750719356");
	}
	@Override
	public Book getBook() {
		return _product;
	}
}
----
****

****
.Reader.java
[source,java]
----
public class Reader {
    public void Create(BookBuilder builder)
    {
        builder.buildIsim();
        builder.buildYazar();
        builder.buildSayfaSayisi();
        builder.buildBasimYili();
        builder.buildYayınEvi();
        builder.buildKategori();
        builder.buildIsbn();
    }
}
----
****

****
.Main.java
[source,java]
----
public class Main {
	public static void main(String[] args) {
		Reader reader = new Reader();
		
		BookBuilder builder = new NovelBuilder();
		reader.Create(builder);
		Book book = builder.getBook();
		System.out.println(book.getOrnek());

		BookBuilder builder2 = new TaleBuilder();
		reader.Create(builder2);
		Book book2 = builder2.getBook();
		System.out.println(book2.getOrnek());
		
		BookBuilder builder3 = new BiographyBuilder();
		reader.Create(builder3);
		Book book3 = builder3.getBook();
		System.out.println(book3.getOrnek());
	}
}
----
****
